### ISSUE TITLE
Предложение

### ISSUE THREAD

**Issue by Tripl0Color** [FallenAstaroth/VK-Bots#9]
Юзаю админ бота
Проблемс, хотелось бы видеть полноценный мут
(сообщение от пользователя 1 - удаление сообщения от пользователя 1)

**Comment by FallenAstaroth** [comment]
> Юзаю админ бота Проблемс, хотелось бы видеть полноценный мут (сообщение от пользователя 1 - удаление сообщения от пользователя 1)

Админ бот находится на рефакторинге. После завершения буду добавлять новые функции, команда мута в планах. Единственное не знаю скок по времени будет, так как сейчас мало времени на пет проекты.
